namespace LockIn9
{
    internal class Program
    {
        static Lock lockObject = new Lock();
        static int i = 0;

        static void Main()
        {
            Thread t1 = new Thread(new ThreadStart(Func1));
            Thread t2 = new Thread(new ThreadStart(Func2));
            Thread t3 = new Thread(new ThreadStart(Func3));
            Thread t4 = new Thread(new ThreadStart(Func4));
            Thread t5 = new Thread(new ThreadStart(Func5));
            t1.Start();
            t2.Start();
            t3.Start();
            t4.Start();
            t5.Start();
        }
        static void Func1()
        {
            using (lockObject.EnterScope())
            {
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;
                Console.WriteLine("First Lock " + i);
                i++;


            }
        }

        static void Func2()
        {
            using (lockObject.EnterScope())
            {
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;
                Console.WriteLine("Second Func" + i);
                i++;

            }
        }

        static void Func3()
        {
            lock (lockObject)
            {
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
                Console.WriteLine("Third Func" + i);
                i++;
            }
        }

        static void Func4()
        {
            lockObject.Enter();
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;
            Console.WriteLine("Fourth Func" + i);
            i++;

            lockObject.Exit();
        }

        static void Func5()
        {
           // Thread.Sleep(1);

            if (lockObject.TryEnter())
            {
                Console.WriteLine("5th Func" + i);
                i++;
                Console.WriteLine("5th Func" + i);
                i++;
                Console.WriteLine("5th Func" + i);
                i++;
                Console.WriteLine("5th Func" + i);
                i++;
                Console.WriteLine("5th Func" + i);
                i++;
                Console.WriteLine("5th Func" + i);
                i++;
                Console.WriteLine("5th Func" + i);
                i++;
                Console.WriteLine("5th Func" + i);
                i++;
                Console.WriteLine("5th Func" + i);
                i++;
                Console.WriteLine("5th Func" + i);
                i++;
                Console.WriteLine("5th Func" + i);
                i++;
                Console.WriteLine("5th Func" + i);
                i++;
                Console.WriteLine("5th Func" + i);
                i++;
                Console.WriteLine("5th Func" + i);
                i++;
                Console.WriteLine("5th Func" + i);
                i++;
                Console.WriteLine("5th Func" + i);
                i++;
                Console.WriteLine("5th Func" + i);
                i++;
                Console.WriteLine("5th Func" + i);
                i++;
                Console.WriteLine("5th Func" + i);
                i++;

                lockObject.Exit();

            }
            else
            {
                Console.WriteLine("Could not enter 5th");
            }
        }
    }
}
