namespace SynchronizationInThreads
{
    internal class Program
    {
        static int i = 0;
        static object lockObject = new object();

        static void Main()
        {
            Thread t1 = new Thread(FuncLock);
            t1.Start();
            Thread t2 = new Thread(FuncMonitor);
            t2.Start();
        }
        static void FuncLock()
        {
            lock (lockObject) //Monitor.Enter(lockObject)
            {
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                //--------------------------
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;


                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                //--------------------------
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;


                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
                i++;
                Console.WriteLine("First FuncLock " + i);
            }
        }
        static void FuncMonitor()
        {
            Monitor.Enter(lockObject);
            //{
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            i++;
            Console.WriteLine("Second Monitor " + i.ToString());
            // }
            Monitor.Exit(lockObject);

        }

        static void InterlockedExamples()
        {
            Interlocked.Add(ref i, 10);
            //i+=10
            Interlocked.Increment(ref i);
            //i++;
            Interlocked.Decrement(ref i);
            //i--;
            Interlocked.Exchange(ref i, 10);
            //i = 10;
        }
    }
}
